#pragma kernel CSMain

#define MAX_WAVES 355

float _Time;
float _DeltaTime;
float2 _PlaneSize;
float _TextureSize;

RWTexture2D<float> Result;
struct Wave
{
    float2 direction;
    float amplitude;
    float wavelength;
    float speed;
};
StructuredBuffer<Wave> _Waves;

float3 DomainWarp(float3 worldPos, float2 normDir, float frequency, float phase, Wave wave, float lastFrame)
{
    float cos_val = cos(dot(normDir, worldPos.xz) * frequency + lastFrame * phase);
    float derivative = frequency * wave.amplitude * cos_val;
    float ddx = derivative * normDir.x;
    float ddy = derivative * normDir.y;
    return float3 (ddx, 0, ddy);
}

float SineWave(float3 worldPos, Wave wave)
{
    float frequency = 6.28318 / wave.wavelength; // 2 * PI / wavelength
    float phase = frequency * wave.speed;
    float2 normDir = normalize(wave.direction);
    float lastFrame = _Time - _DeltaTime;
    float3 previousePosition = DomainWarp(worldPos, normDir, frequency, phase, wave, lastFrame);
    float sine = sin(dot(normDir, worldPos.xz + previousePosition.xz) * frequency + _Time * phase);
    
    return wave.amplitude * (pow(2.71828, sine) - 1);
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 uv = id.xy / _TextureSize;
    float2 worldPosXZ = (uv - 0.5) * _PlaneSize;
    float3 worldPos = float3(worldPosXZ.x, 0.0, worldPosXZ.y);
    float totalHeight = 0;
    uint count, strideBytes;
    _Waves.GetDimensions(count, strideBytes);
    count = min(count, MAX_WAVES);
    // Perform the exact same loop as the visual shader
    for (int i = 0; i < count; i++)
    {
        totalHeight += SineWave(worldPos, _Waves[i]);
    }
    
    Result[id.xy] = totalHeight;
}
