#pragma kernel CSMain

#define MAX_WAVES 355

float _Time;
float2 _PlaneSize;
float _TextureSize;

RWTexture2D<float> Result;
struct Wave
{
    float2 direction;
    float amplitude;
    float wavelength;
    float speed;
};
StructuredBuffer<Wave> _Waves;

float SineWave(float3 worldPos, float time, Wave wave)
{
    float frequency = 6.28318 / wave.wavelength; // 2 * PI / wavelength
    float phase = frequency * wave.speed;
    float sine = sin(dot(normalize(wave.direction), worldPos.xz) * frequency + time * phase);
    
    //return (pow(2.71828, sine) - 1)
    return sine * wave.amplitude;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 uv = id.xy / _TextureSize;
    float2 worldPosXZ = (uv - 0.5) * _PlaneSize;
    float3 worldPos = float3(worldPosXZ.x, 0.0, worldPosXZ.y);
    float totalHeight = 0;
    uint count, strideBytes;
    _Waves.GetDimensions(count, strideBytes);
    count = min(count, MAX_WAVES);
    // Perform the exact same loop as the visual shader
    for (int i = 0; i < count; i++)
    {
        totalHeight += SineWave(worldPos, _Time, _Waves[i]);
    }
    
    Result[id.xy] = totalHeight;
}
